language: python
python:
  - "3.8"
install:
  - pip install .
  - pip install -r requirements.txt
  - pip install coverage
  - pip install pylint
  - pip install pytest
  - git clone https://github.com/kerrickstaley/genanki; cd genanki; python setup.py install; cd ..
jobs:
  include:
    - name: project-1
      python: "3.8"
script:
  - python -m pytest -v test/
  - coverage run --source ./code/ -m pytest -v ./test/
  - pylint code/
after_success:
  - bash <(curl -s https://codecov.io/bash)
