name: Build

on: [push, pull_request]

jobs:
  flake8:
    runs-on: ubuntu-latest
    steps:
      - name: Check out code
        uses: actions/checkout@v2
      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: 3.11
      - name: Install Dependencies
        run: |
          python -m pip install --upgrade pip
          pip install flake8
      - name: Run flake8
        run: |
          flake8 .
      - name: Upload coverage reports to Codecov
        run: bash <(curl -s https://codecov.io/bash) -t 9ed4024e-0d99-482b-9214-a5c2f40dc033
